
DELETE FROM PERSON;
DELETE FROM TRACK;
TRUNCATE TABLE ALBUM;
TRUNCATE TABLE ALBUM_PLAYLIST;
TRUNCATE TABLE COMMENTS;
TRUNCATE TABLE HISTORY;
TRUNCATE TABLE LIKES_ALBUM;
TRUNCATE TABLE PLAYLIST;
TRUNCATE TABLE SUBSCRIPTION;
TRUNCATE TABLE TRACK_ALBUM;
TRUNCATE TABLE TRACK_PLAYLIST;
TRUNCATE TABLE TYPE_PREFERENCES;
DELETE FROM LIKES_TRACK;
DELETE FROM TYPE;
commit;