 CREATE TABLE "MMF_9_5"."DATA_T" 
   (	"FIRST_NAME" VARCHAR2(100 BYTE), 
	"LAST_NAME" VARCHAR2(100 BYTE), 
	"NICKNAME" VARCHAR2(100 BYTE), 
	"EMAIL" VARCHAR2(100 BYTE), 
	"PLAYLIST_NAME" VARCHAR2(100 BYTE), 
	"PLAYLIST_TYPE" VARCHAR2(100 BYTE), 
	"MUSIC_TYPE" VARCHAR2(100 BYTE), 
	"COMPOSITION_NAME" VARCHAR2(256 BYTE), 
	"Length" VARCHAR2(26 BYTE), 
	"OWNER_FIRST_NAME" VARCHAR2(100 BYTE), 
	"OWNER_LAST_NAME" VARCHAR2(100 BYTE), 
	"OWNER_NICKNAME" VARCHAR2(100 BYTE), 
	"Like" VARCHAR2(26 BYTE), 
	"COMPOSITION_LIKES" NUMBER(38,0), 
	"LISTEN" NUMBER(38,0), 
	"COMMENTS_TRACK" VARCHAR2(100 BYTE), 
	"CURRENT_LISTENING" VARCHAR2(26 BYTE), 
	"STOPPED_TIME" VARCHAR2(26 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MMF_9_5_DATA" ;

Insert into DATA_T (FIRST_NAME,LAST_NAME,NICKNAME,EMAIL,PLAYLIST_NAME,PLAYLIST_TYPE,MUSIC_TYPE,COMPOSITION_NAME,"Length",OWNER_FIRST_NAME,OWNER_LAST_NAME,OWNER_NICKNAME,"Like",COMPOSITION_LIKES,LISTEN,COMMENTS_TRACK,CURRENT_LISTENING,STOPPED_TIME) values ('Владислав','Кисляков','Chewbaca','ChewbacaMorning@gmail.com','Morning','User','Electronic','Nicolas Jaar - El Bandido','6.37','Oleg','Synytsky','Dreamboat','yes','2126','108000','Nah not feelin it',null,null);
Insert into DATA_T (FIRST_NAME,LAST_NAME,NICKNAME,EMAIL,PLAYLIST_NAME,PLAYLIST_TYPE,MUSIC_TYPE,COMPOSITION_NAME,"Length",OWNER_FIRST_NAME,OWNER_LAST_NAME,OWNER_NICKNAME,"Like",COMPOSITION_LIKES,LISTEN,COMMENTS_TRACK,CURRENT_LISTENING,STOPPED_TIME) values ('Владислав','Кисляков','Chewbaca','ChewbacaMorning@gmail.com','Morning','User','Electronic','Electro - Trance - House','4.09­','Oleg','Synytsky','Dreamboat','no','4005','5055',null,null,null);
Insert into DATA_T (FIRST_NAME,LAST_NAME,NICKNAME,EMAIL,PLAYLIST_NAME,PLAYLIST_TYPE,MUSIC_TYPE,COMPOSITION_NAME,"Length",OWNER_FIRST_NAME,OWNER_LAST_NAME,OWNER_NICKNAME,"Like",COMPOSITION_LIKES,LISTEN,COMMENTS_TRACK,CURRENT_LISTENING,STOPPED_TIME) values ('Владислав','Кисляков','Chewbaca','ChewbacaMorning@gmail.com','Morning','User','Electronic','Nice Night','5.21','Oleg','Synytsky','Dreamboat','yes','88','82000','NIGGER!!!!','Y','1.02');
Insert into DATA_T (FIRST_NAME,LAST_NAME,NICKNAME,EMAIL,PLAYLIST_NAME,PLAYLIST_TYPE,MUSIC_TYPE,COMPOSITION_NAME,"Length",OWNER_FIRST_NAME,OWNER_LAST_NAME,OWNER_NICKNAME,"Like",COMPOSITION_LIKES,LISTEN,COMMENTS_TRACK,CURRENT_LISTENING,STOPPED_TIME) values ('Владислав','Кисляков','Chewbaca','ChewbacaMorning@gmail.com','Morning','User','Electronic','Electro 2020','10.05','Christian','Radaelli','Dumpling','no','231','99548','Sadie is my dog',null,null);
Insert into DATA_T (FIRST_NAME,LAST_NAME,NICKNAME,EMAIL,PLAYLIST_NAME,PLAYLIST_TYPE,MUSIC_TYPE,COMPOSITION_NAME,"Length",OWNER_FIRST_NAME,OWNER_LAST_NAME,OWNER_NICKNAME,"Like",COMPOSITION_LIKES,LISTEN,COMMENTS_TRACK,CURRENT_LISTENING,STOPPED_TIME) values ('Владислав','Кисляков','Chewbaca','ChewbacaMorning@gmail.com','Morning','User','Electronic','REMIX BOLICHEROS 2019!!!','8.01','Christian','Radaelli','Dumpling','yes','84','32001',null,null,null);
Insert into DATA_T (FIRST_NAME,LAST_NAME,NICKNAME,EMAIL,PLAYLIST_NAME,PLAYLIST_TYPE,MUSIC_TYPE,COMPOSITION_NAME,"Length",OWNER_FIRST_NAME,OWNER_LAST_NAME,OWNER_NICKNAME,"Like",COMPOSITION_LIKES,LISTEN,COMMENTS_TRACK,CURRENT_LISTENING,STOPPED_TIME) values ('Елизавета','Рапинчук','Bug','Circle_Bug@gmail.com','Sport','System','Sport','Drifting','2.11','Ten','Walls','Monsieur','no','34','806','Jesus christ',null,null);
Insert into DATA_T (FIRST_NAME,LAST_NAME,NICKNAME,EMAIL,PLAYLIST_NAME,PLAYLIST_TYPE,MUSIC_TYPE,COMPOSITION_NAME,"Length",OWNER_FIRST_NAME,OWNER_LAST_NAME,OWNER_NICKNAME,"Like",COMPOSITION_LIKES,LISTEN,COMMENTS_TRACK,CURRENT_LISTENING,STOPPED_TIME) values ('Елизавета','Рапинчук','Bug','Circle_Bug@gmail.com','Sport','System','Sport','SESSION #186 (Feat. Ten Walls)','4.02','Ten','Walls','Monsieur','yes','456','1050',null,null,null);
Insert into DATA_T (FIRST_NAME,LAST_NAME,NICKNAME,EMAIL,PLAYLIST_NAME,PLAYLIST_TYPE,MUSIC_TYPE,COMPOSITION_NAME,"Length",OWNER_FIRST_NAME,OWNER_LAST_NAME,OWNER_NICKNAME,"Like",COMPOSITION_LIKES,LISTEN,COMMENTS_TRACK,CURRENT_LISTENING,STOPPED_TIME) values ('Елизавета','Рапинчук','Bug','Circle_Bug@gmail.com','Sport','System','Pop','Ariana Grande - Side To Side Ft. Nicki Minaj (Remix)','3.12','Kelvin','Pasman','Snuggy','no','1102','1526','another classic',null,null);
Insert into DATA_T (FIRST_NAME,LAST_NAME,NICKNAME,EMAIL,PLAYLIST_NAME,PLAYLIST_TYPE,MUSIC_TYPE,COMPOSITION_NAME,"Length",OWNER_FIRST_NAME,OWNER_LAST_NAME,OWNER_NICKNAME,"Like",COMPOSITION_LIKES,LISTEN,COMMENTS_TRACK,CURRENT_LISTENING,STOPPED_TIME) values ('Елизавета','Рапинчук','Bug','Circle_Bug@gmail.com','Sport','System','Pop','Major Lazer - Too Original (Remix)','2.45','Kelvin','Pasman','Snuggy','yes','358','1200','адский разгон',null,null);
Insert into DATA_T (FIRST_NAME,LAST_NAME,NICKNAME,EMAIL,PLAYLIST_NAME,PLAYLIST_TYPE,MUSIC_TYPE,COMPOSITION_NAME,"Length",OWNER_FIRST_NAME,OWNER_LAST_NAME,OWNER_NICKNAME,"Like",COMPOSITION_LIKES,LISTEN,COMMENTS_TRACK,CURRENT_LISTENING,STOPPED_TIME) values ('Елизавета','Рапинчук','Bug','Circle_Bug@gmail.com','Sport','System','Sport','Ten Walls - Sparta','3.44','Ten','Walls','Monsieur','no','88','22000','Очень серьезный кач','Y','2.01');
Insert into DATA_T (FIRST_NAME,LAST_NAME,NICKNAME,EMAIL,PLAYLIST_NAME,PLAYLIST_TYPE,MUSIC_TYPE,COMPOSITION_NAME,"Length",OWNER_FIRST_NAME,OWNER_LAST_NAME,OWNER_NICKNAME,"Like",COMPOSITION_LIKES,LISTEN,COMMENTS_TRACK,CURRENT_LISTENING,STOPPED_TIME) values ('Елизавета','Рапинчук','Bug','Circle_Bug@gmail.com','Bamboo','User','Chill','Murda On They Mind (Tales From Mount Zion)','3.02','Den','Philips','DJ Bishop','yes','3306','540050',null,null,null);
Insert into DATA_T (FIRST_NAME,LAST_NAME,NICKNAME,EMAIL,PLAYLIST_NAME,PLAYLIST_TYPE,MUSIC_TYPE,COMPOSITION_NAME,"Length",OWNER_FIRST_NAME,OWNER_LAST_NAME,OWNER_NICKNAME,"Like",COMPOSITION_LIKES,LISTEN,COMMENTS_TRACK,CURRENT_LISTENING,STOPPED_TIME) values ('Елизавета','Рапинчук','Bug','Circle_Bug@gmail.com','Bamboo','User','Electronic','James Blake - Air'||chr(38)||'Lack Thereof','4.09­','Hélder','Leal','Hotshot','no','4455','1433',null,null,null);
Insert into DATA_T (FIRST_NAME,LAST_NAME,NICKNAME,EMAIL,PLAYLIST_NAME,PLAYLIST_TYPE,MUSIC_TYPE,COMPOSITION_NAME,"Length",OWNER_FIRST_NAME,OWNER_LAST_NAME,OWNER_NICKNAME,"Like",COMPOSITION_LIKES,LISTEN,COMMENTS_TRACK,CURRENT_LISTENING,STOPPED_TIME) values ('Елизавета','Рапинчук','Bug','Circle_Bug@gmail.com','Bamboo','User','Electronic','Little Fish','2.13','Hélder','Leal','Hotshot','yes','6587','8890',null,null,null);
Insert into DATA_T (FIRST_NAME,LAST_NAME,NICKNAME,EMAIL,PLAYLIST_NAME,PLAYLIST_TYPE,MUSIC_TYPE,COMPOSITION_NAME,"Length",OWNER_FIRST_NAME,OWNER_LAST_NAME,OWNER_NICKNAME,"Like",COMPOSITION_LIKES,LISTEN,COMMENTS_TRACK,CURRENT_LISTENING,STOPPED_TIME) values ('Елизавета','Рапинчук','Bug','Circle_Bug@gmail.com','Bamboo','User','Electronic','Jamie XX - Loud Places (feat. Romy)','4.43','Hélder','Leal','Hotshot','no','2201','202023',null,null,null);
commit;