ALTER TABLE PLAYLIST 
ADD (NAME VARCHAR2(50) );

ALTER TABLE TRACK 
ADD (NAME VARCHAR2(100) );

ALTER TABLE TRACK  
MODIFY (DURATION VARCHAR2(20) );

ALTER TABLE HISTORY  
MODIFY (PAUSED_TIME VARCHAR2(20) );